apiVersion: v1
data:
  secret: {{ required "A value ceph.adminKey is required." .Values.ceph.adminKey | b64enc | quote }}
kind: Secret
metadata:
  name: ceph-admin-secret-{{ .Release.Name }}
  namespace: kube-system
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
